USE alx_book_store;

SELECT COLUMN_NAME,
    COLUMN_TYPE,
    COLUMN_KEY,
    COLUMN_DEFAULT,
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
AND TABLE_NAME = 'books'
ORDER BY ORIGINAL_POSITION;

